"""empty message

Revision ID: 147c7a9c57b
Revises: 224f3859cb2
Create Date: 2015-12-13 13:03:45.936956

"""

# revision identifiers, used by Alembic.
revision = '147c7a9c57b'
down_revision = '224f3859cb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
