"""empty message

Revision ID: 1c2bd29ba0
Revises: 147c7a9c57b
Create Date: 2015-12-13 13:59:54.040128

"""

# revision identifiers, used by Alembic.
revision = '1c2bd29ba0'
down_revision = '147c7a9c57b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    op.drop_table('category')
    ### end Alembic commands ###
